### ISSUE TITLE
Support for Batch Processing and Inference on GPU

### ISSUE THREAD

**Issue by murthyrudra** [AI4Bharat/IndianNLP-Transliteration#5]
Hi, thanks for the transliteration api. It's helpful. 

1. Is it possible to transliterate words in batches rather than one at a time?
2. Also, can there be a flag in API where the model can use GPU if available?

**Comment by khatrimann** [comment]
+1

**Comment by khatrimann** [comment]
A temporary thing which can be done is goto ```xlit_src.py``` and change all ```device="cpu"``` to ```device="cuda"```

**Comment by JosephGeoBenjamin** [comment]
@khatrimann changing the device to Cuda will not be possible because of how inferencing is handled in this project. 
During decoding Active beam search is used in a way that toggling memory between GPU and CPU at that stage, given that throughput would be small, would be more costly than using a CPU alone.

**Comment by JosephGeoBenjamin** [comment]
Please Check the latest Transformer version of Transliteration Models in this Project: https://github.com/AI4Bharat/IndicXlit

This has improved unified language models and GPU support as well
